#!/usr/bin/env bash
set -euo pipefail
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=api_password="$PLANNER_API_PASSWORD" <<'SQL'
CREATE ROLE planner_api LOGIN PASSWORD :'api_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
REVOKE ALL ON DATABASE planner FROM PUBLIC;
GRANT CONNECT ON DATABASE planner TO planner_api;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO planner_api;
ALTER DEFAULT PRIVILEGES FOR ROLE planner_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO planner_api;
ALTER DEFAULT PRIVILEGES FOR ROLE planner_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO planner_api;
SQL
